services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/bin/app
    command: air --build.cmd "go build -o build/oflow-server cmd/main.go" --build.bin "build/oflow-server"
